fix: yml

diff --git a/.github/workflows/main_ragprwebapps.yml b/.github/workflows/main_ragprwebapps.yml
--- a/.github/workflows/main_ragprwebapps.yml
+++ b/.github/workflows/main_ragprwebapps.yml
@@ -1,6 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
 name: Build and deploy Node.js app to Azure Web App - ragprwebapps
 
 on:
@@ -40,8 +37,8 @@ jobs:
 
       - name: Zip artifact for deployment
         run: |
-          cd fe
-          zip release.zip ./deploy -r
+          cd fe/deploy
+          zip -r ../release.zip .
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
@@ -54,7 +51,6 @@ jobs:
     needs: build
     environment:
       name: 'Production'
-      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
       id-token: write
 
@@ -65,7 +61,14 @@ jobs:
           name: node-app
 
       - name: Unzip artifact for deployment
-        run: unzip release.zip
+        run: unzip release.zip -d deploy
+      
+      - name: Verify server.js
+        run: |
+          if [ ! -f "./deploy/server.js" ]; then
+            echo "Error: server.js not found in deploy directory"
+            exit 1
+          fi
       
       - name: Login to Azure
         uses: azure/login@v2
@@ -80,5 +83,4 @@ jobs:
         with:
           app-name: 'ragprwebapps'
           slot-name: 'Production'
-          package: .
-          
+          package: ./deploy
